### ISSUE TITLE
Cannot start a previously stoped container

### ISSUE THREAD

**Issue by sebagomez** [Microsoft/aspnet-docker#38] opened 2017-06-30 22:20 UTC
I have a Dockerfile based on `FROM microsoft/mssql-server-windows-developer:2016-sp1` where I then add the asp.net features. It looks pretty much like this:

    FROM microsoft/mssql-server-windows-developer:2016-sp1
    ENV ACCEPT_EULA=Y sa_password=Passw0rd
     
    RUN powershell -Command \
      $ErrorActionPreference = 'Stop'; \
      $ProgressPreference = 'SilentlyContinue'; \
      Add-WindowsFeature Web-Server; \
      Add-WindowsFeature NET-Framework-45-ASPNET; \
      Add-WindowsFeature Web-Asp-Net45; \
      Remove-Item -Recurse C:\inetpub\wwwroot\*;\
      Remove-Item -Recurse C:\dockerfile

    ADD https://github.com/Microsoft/iis-docker/raw/master/windowsservercore/ServiceMonitor.exe /

    EXPOSE 1433 80

    ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]

The image gets created with no problem and when I run the image (to create a container) I run this command, attaching a local host directory as a volume where the IIS reads my site.
`docker run -d -v C:\MyDir\web:C:\inetpub\wwwroot\ --name mycontainer myimage`

Everything works fine, until I stop the container. I the want to start it again with this command `docker start mycontainer` but I get the following error: 

    ERROR ( message:New add object missing required attributes. Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'ACCEPT_EULA'. )
    APPCMD failed with error code 183
    Failed to update IIS configuration

Can anybody help me with that, what's going on? What is the start command trying to do messing up the web.config (?)
ACCEPT_EULA is one of the needed environment variables to run the SQL Server image.

**Comment by LouisDK** [comment] 2017-07-02 12:30
I have a similar problem, or at least, I believe the root cause is the same as what @sebagomez reports above.

I'm using a docker container built with FROM microsoft/aspnet:4.7 

Everything works when I create/run it for the first time, but when I stop the container, and start it again, it fails to start, reporting: ERROR ( message:New add object missing required attributes. Cannot add duplicate collection entry of type 'add' with unique key attribute 'name' set to 'ALLUSERSPROFILE'
APPCMD failed with error code 183
Failed to update IIS configuration

The Container then exits.

My scenario involves using docker-compose. When I run docker-compose up, everything works, but when I stop everything, and run docker-compose up for a second time, I get the error above.

My Dockerfile:
# escape=`
FROM microsoft/aspnet:4.7 
ADD ./webapp /inetpub/wwwroot

**Comment by shirhatti** [comment] 2017-07-05 17:57
This is dupe of https://github.com/Microsoft/iis-docker/issues/42 and is being tracked there. We are aware of the regression we introduced with a change to `ServiceMonitor.exe` and should have a fix out shortly.

**Closed by shirhatti** 2017-07-05 17:57 UTC

**Comment by sebagomez** [comment] 2017-07-05 18:34
this issue was filed before the one being tracked :( why is that?
