### ISSUE TITLE
Dockerfile linked from hub.docker.com/r/microsoft/aspnet is incorrect

### ISSUE THREAD

**Issue by mjrousos** [Microsoft/aspnet-docker#42] opened 2017-07-13 21:37 UTC
On the [microsoft/aspnet](https://hub.docker.com/r/microsoft/aspnet) Docker Hub page, there's a Dockerfile tab but [the Dockerfile shown](https://hub.docker.com/r/microsoft/aspnet/~/dockerfile/) when following the link is not a microsoft/aspnet Dockerfile. It looks like an old Linux ASP.NET Core/DNX Dockerfile. The Dockerfile link should probably just be removed (or, at least, point to an up-to-date aspnet Dockerfile).

**Comment by shirhatti** [comment] 2017-08-16 22:04
Dupe of #2

**Closed by shirhatti** 2017-08-16 22:04 UTC
