### ISSUE TITLE
Unable to read environment variables defined in Dockerfile in asp.net site

### ISSUE THREAD

**Issue by sherland** [Microsoft/aspnet-docker#7] opened 2016-10-13 12:20 UTC
Not sure if this is a problem with docker, the base-image or this image.
Also see this stackoverflow question: [http://stackoverflow.com/questions/39978342/docker-for-windows-asp-net-site-unable-to-read-environment-variables-defined-in](http://stackoverflow.com/questions/39978342/docker-for-windows-asp-net-site-unable-to-read-environment-variables-defined-in)

First create a container based on Dockerfile and default.aspx in 
[test.zip](https://github.com/Microsoft/aspnet-docker/files/527022/test.zip)

Then start powershell in the container, and verify that powershell can see the externaly defined environment variables:

    docker run -it --rm -e FROM_COMMAND_LINE="From command line" --entrypoint powershell test

As expected the environment variables are available:

    PS C:\> $env:FROM_COMMAND_LINE
    From command line
    PS C:\> $env:FROM_DOCKERFILE
    Value from dockerfile

However, when fetching the aspx file, the environment variables are NOT available: (The behavior is the same after iisreset inside the container)

    PS C:\> $(wget http://localhost/default.aspx -UseBasicParsing).Content
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx GetEnvironmentVariables
    COMPUTERNAME - 540CA54CDB93<br>
    PUBLIC - C:\Users\Public<br>
    LOCALAPPDATA - C:\Windows\system32\config\systemprofile\AppData\Local<br>
    ...
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx GetEnvironmentVariables - Process
    COMPUTERNAME - 540CA54CDB93<br>
    PUBLIC - C:\Users\Public<br>
    LOCALAPPDATA - C:\Windows\system32\config\systemprofile\AppData\Local<br>
    ...
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx GetEnvironmentVariables - User
    Path - C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;<br>
    TEMP - C:\Windows\system32\config\systemprofile\AppData\Local\Temp<br>
    TMP - C:\Windows\system32\config\systemprofile\AppData\Local\Temp<br>
    
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx GetEnvironmentVariables - Machine
    PROCESSOR_REVISION - 3f02<br>
    ...

**Comment by shirhatti** [comment] 2016-10-13 21:47
@shreland Thanks for reporting this.

Environment variables passed to `docker` through `-e` are set for the process in the container via [`CreateProcess` and `lpEnvironment`.](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx)

They are not set as SYSTEM Variables which would reside in the registry in the `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment` hive and hence `w3wp.exe` won't pick up the changes even you run `iisreset`.

You have a couple of workaround options here:
- You could create a SYSTEM variable by running `RUN setx /m VAR val` in your Dockerfile. This would be picked by your IIS Worker Process after you run `iisreset`.
- Create an environment variable only for that AppPool as alluded to in this [comment](https://github.com/Microsoft/iis-docker/issues/2#issuecomment-251794255). `RUN appcmd.exe set config -section:system.applicationHost/applicationPools /+"[name='DefaultAppPool'].environmentVariables.[name='VAR',value='val']" /commit:apphost`.

**Comment by shirhatti** [comment] 2016-10-13 21:57
We realize this is not ideal at the moment and are looking at ways to flow environment variables from `docker run -e VAR=val` all the way to your app. I'm going to close this issue as a duplicate of https://github.com/Microsoft/iis-docker/issues/2

**Closed by shirhatti** 2016-10-13 21:57 UTC
